# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:18
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import likert_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Non-Fiction', (('Biography', 'Biography'), ('Business', 'Business'), ('Computer', 'Computer'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Food', 'Food & Beverages'), ('History', 'History'), ('Law', 'Law'), ('Manga', 'Manga'), ('Medical', 'Medical'), ('Novel', 'Novel'), ('Religion', 'Religion'), ('Sports', 'Sports'), ('Technology', 'Technology'))), ('Fiction', (('Action', 'Action'), ('Adventure', 'Adventure'), ('Classics', 'Classics'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('ScienceFiction', 'Science Fiction'), ('Thrillers', 'Thrillers'))), ('School Books', (('Secondary', 'Secondary'), ('Primary', 'Primary'), ('Polytechnic', 'Polytechnic'), ('juniorcollege', 'Junior College'), ('university', 'University')))], max_length=100)),
                ('description', models.TextField()),
                ('personal_review', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('condition', likert_field.models.LikertField(blank=True, null=True)),
                ('slug', models.SlugField(default=django.utils.crypto.get_random_string, max_length=13, unique=True)),
                ('sold', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(blank=True, choices=[('Good', 'Good'), ('Neutral', 'Neutral'), ('Bad', 'Bad')], max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='user', unique=True)),
                ('shelf', models.ManyToManyField(blank=True, related_name='shelf_set', to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='books.UserProfile'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
