# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160409_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Non-Fiction', (('Biography', 'Biography'), ('Business', 'Business'), ('Computing', 'Computing'), ('Design', 'Design'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Food', 'Food'), ('History', 'History'), ('Law', 'Law'), ('Religion', 'Religion'), ('Science', 'Science'), ('Sports', 'Sports'), ('Technology', 'Technology'))), ('Fiction', (('Action', 'Action'), ('Comic', 'Comic'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Novels', 'Novels'), ('Romance', 'Romance'), ('sciencefiction', 'Science Fiction'))), ('Others', (('Others', 'Others'),))], max_length=100),
        ),
    ]
