# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160131_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
