# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160204_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Non-Fiction', (('Biography', 'Biography'), ('Business/Finance', 'Business'), ('Computing', 'Computing'), ('Fiction', 'Fiction'), ('Food & Beverages', 'Food & Beverages'), ('Graphic novels/Manga', 'Graphic novels/Manga'), ('History', 'History'), ('Law', 'Law'), ('Medical', 'Medical'), ('Religion', 'Religion'), ('Sports', 'Sports'), ('Technology & Engineering', 'Technology & Engineering'))), ('Fiction', (('Adventure', 'Adventure'), ('Classics', 'Classics'), ('Contemporary Fiction', 'Contemporary Fiction'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thrillers', 'Thrillers'))), ('School Textbooks', (('math', 'math'),))], max_length=100),
        ),
    ]
