# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shelf',
            field=models.ManyToManyField(blank=True, related_name='shelf_set', to='books.Book'),
        ),
    ]
