# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160206_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
