# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160206_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='book',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='book',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='book',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Non-Fiction', (('Biography', 'Biography'), ('Business', 'Business'), ('Computer', 'Computer'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Food', 'Food & Beverages'), ('History', 'History'), ('Law', 'Law'), ('Manga', 'Manga'), ('Medical', 'Medical'), ('Novel', 'Novel'), ('Religion', 'Religion'), ('Sports', 'Sports'), ('Technology', 'Technology'))), ('Fiction', (('Action', 'Action'), ('Adventure', 'Adventure'), ('Classics', 'Classics'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('ScienceFiction', 'Science Fiction'), ('Thrillers', 'Thrillers'))), ('School Books', (('Secondary', 'Secondary'), ('Primary', 'Primary'), ('Polytechnic', 'Polytechnic'), ('juniorcollege', 'Junior College'), ('university', 'University')))], max_length=100),
        ),
    ]
