# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:52
from __future__ import unicode_literals

from django.db import migrations
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=likert_field.models.LikertField(blank=True, null=True),
        ),
    ]
