# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 07:09
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20160217_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
