# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default=django.utils.crypto.get_random_string, max_length=13, unique=True),
        ),
    ]
