# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='book',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('Primary', (('prienglish', 'English'), ('primath', 'Math'), ('prichinese', 'Chinese'), ('primalay', 'Malay'), ('priscience', 'Science'))), ('Secondary', (('secenglish', 'English'), ('secmath', 'Math'), ('secchinese', 'Chinese'), ('secmalay', 'Malay'), ('secscience', 'Science'), ('sechumanities', 'Humanities'))), ('Polytechnic', (('polybusiness', 'Business'), ('polydesign', 'Design'), ('polyengineering', 'Engineering'), ('polyit', 'IT'), ('polymedia', 'Media'), ('polyscience', 'Science'))), ('ITE', (('itebusiness', 'Business'), ('itedesign', 'Design'), ('iteengineering', 'Engineering'), ('iteit', 'IT'), ('itemedia', 'Media'), ('itescience', 'Science'))), ('University', (('unibusiness', 'Business'), ('unidesign', 'Design'), ('uniengineering', 'Engineering'), ('uniit', 'IT'), ('unimedia', 'Media'), ('uniscience', 'Science')))], max_length=100),
        ),
    ]
