# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20160409_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('Primary', (('prienglish', 'English'), ('primath', 'Math'), ('primothertongue', 'Mother Tongue'), ('priscience', 'Science'))), ('Secondary', (('secenglish', 'English'), ('secmath', 'Math'), ('secmothertongue', 'Mother Tongue'), ('secscience', 'Science'), ('sechumanities', 'Humanities'))), ('Junior College', (('jcgp', 'General Paper'), ('jcmath', 'Math'), ('jcmothertongue', 'Mother Tongue'), ('jcscience', 'Science'), ('jchumanities', 'Humanities'))), ('Polytechnic', (('polybusiness', 'Business'), ('polydesign', 'Design'), ('polyengineering', 'Engineering'), ('polyit', 'IT'), ('polymedia', 'Media'), ('polyscience', 'Science'))), ('ITE', (('itebusiness', 'Business'), ('itedesign', 'Design'), ('iteengineering', 'Engineering'), ('iteit', 'IT'), ('itemedia', 'Media'), ('itescience', 'Science'))), ('University', (('unibusiness', 'Business'), ('unidesign', 'Design'), ('uniengineering', 'Engineering'), ('uniit', 'IT'), ('unimedia', 'Media'), ('uniscience', 'Science')))], max_length=100),
        ),
    ]
