# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default=django.utils.crypto.get_random_string, max_length=13, unique=True),
        ),
    ]
